### ISSUE TITLE
recursive?

### ISSUE THREAD

**Issue by AlJohri** [pcattori/maps#35]
I was wondering if you can export a recursive version that can handle recurse into dicts and lists.

Here is an example structure I am working with:
![screen shot 2017-03-27 at 3 59 36 pm](https://cloud.githubusercontent.com/assets/2790092/24375503/7e5d64d6-1306-11e7-8439-49f202093cf4.png)

I envision this to be similar to the `fromJS` function from immutableJS: http://facebook.github.io/immutable-js/docs/#/fromJS

EDIT: I meant to use `FrozenMap` in the screenshot above.

**Comment by AlJohri** [comment]
Here's a simple implementation of what I'm talking about:

```python
import collections
from maps import FrozenMap

def freeze(x, frozen_map_fn=FrozenMap, frozen_list_fn=tuple):
    klass = type(x)
    if isinstance(x, collections.Mapping):
        new_x = frozen_map_fn(klass((k,freeze(v)) for k,v in x.items()))
    elif not isinstance(x, str) and (isinstance(x, collections.Sequence) or isinstance(x, collections.Set)):
        new_x = frozen_list_fn(klass(freeze(v) for v in x))
    else:
        new_x = x
    return new_x
```

Let me know if you see anything missing.

**Comment by AlJohri** [comment]
Updated implementation to carry over kwargs and be more general:

```python
def recurse(x, map_fn=lambda x: x, list_fn=lambda x: x, object_fn=lambda x: x):
    kwargs = {"map_fn": map_fn, "list_fn": list_fn, "object_fn": object_fn}
    klass = type(x)
    if isinstance(x, collections.Mapping):
        new_x = map_fn(klass((k,recurse(v, **kwargs)) for k,v in x.items()))
    elif not isinstance(x, str) and (isinstance(x, collections.Sequence) or isinstance(x, collections.Set)):
        new_x = list_fn(klass(recurse(v, **kwargs) for v in x))
    elif not isinstance(x, (int, float, str, bool)):
        new_x = object_fn(x)
    else:
        new_x = x
    return new_x

def freeze(x, **kwargs):
    return recurse(x, map_fn=FrozenMap, list_fn=tuple)

def namespace(x, **kwargs):
    return recurse(x, map_fn=NamedDict)
```

**Comment by AlJohri** [comment]
thanks @pcattori!

**Comment by pcattori** [comment]
check docs for usage, e.g. for [recursively-created `FrozenMaps`](http://maps.readthedocs.io/en/latest/api.html#maps.FrozenMap.recurse)
