### ISSUE TITLE
[Feature Request] FrozenMap.update

### ISSUE THREAD

**Issue by mvcisback** [pcattori/maps#46]
Hi,
Would it be possible to add a binary operation between `FrozenMap` instances that merges them?
For example, it would be nice for the following code to work:
```python
import maps
x = maps.FrozenMap({'a': 2, 'b': 4})
y = maps.FrozenMap({'b': 5, 'c': 6})
assert x.update(y) == maps.FrozenMap({'a': 2, 'b': 5, 'c': 6})
assert x['b'] == 4
assert 'c' not in x
```

**Comment by pcattori** [comment]
@mvcisback you can do this with Python 3 via [Extended Iterable Unpacking](https://www.python.org/dev/peps/pep-3132/)

```python
import maps
x = maps.FrozenMap({'a': 2, 'b': 4})
y = maps.FrozenMap({'b': 5, 'c': 6})
assert maps.FrozenMap({**x, **y}) == maps.FrozenMap({'a': 2, 'b': 5, 'c': 6})
assert x['b'] == 4
assert 'c' not in x
```

---

Does that address your use-case?

**Comment by mvcisback** [comment]
That's a good work around. Thanks.
